"""v0.2 ux data fields

Revision ID: a72d333806d3
Revises: 190f6b3cffb2
Create Date: 2026-06-28 22:12:24.618923
"""

from alembic import op
import sqlalchemy as sa


revision = 'a72d333806d3'
down_revision = '190f6b3cffb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('care_requests', sa.Column('visit_time', sa.String(length=20), nullable=False, server_default='09:00'))
    op.add_column('care_requests', sa.Column('language', sa.String(length=80), nullable=True))
    op.add_column('care_requests', sa.Column('gender_preference', sa.String(length=40), nullable=True))
    op.add_column('care_requests', sa.Column('recurring', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('care_requests', sa.Column('emergency_request', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('caretakers', sa.Column('experience_years', sa.Integer(), nullable=False, server_default='6'))
    op.add_column('caretakers', sa.Column('verified', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('medicines', sa.Column('brand', sa.String(length=120), nullable=True))
    op.add_column('medicines', sa.Column('pack_size', sa.String(length=80), nullable=False, server_default='10 tablets'))
    op.add_column('medicines', sa.Column('minimum_stock', sa.Integer(), nullable=False, server_default='20'))
    op.add_column('medicines', sa.Column('barcode', sa.String(length=80), nullable=True))
    op.add_column('medicines', sa.Column('expiry_placeholder', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medicines', 'expiry_placeholder')
    op.drop_column('medicines', 'barcode')
    op.drop_column('medicines', 'minimum_stock')
    op.drop_column('medicines', 'pack_size')
    op.drop_column('medicines', 'brand')
    op.drop_column('caretakers', 'verified')
    op.drop_column('caretakers', 'experience_years')
    op.drop_column('care_requests', 'emergency_request')
    op.drop_column('care_requests', 'recurring')
    op.drop_column('care_requests', 'gender_preference')
    op.drop_column('care_requests', 'language')
    op.drop_column('care_requests', 'visit_time')
    # ### end Alembic commands ###
