"""v0.2 final refinement fields

Revision ID: fd63ab5ecf74
Revises: a72d333806d3
Create Date: 2026-06-28 22:44:59.586691
"""

from alembic import op
import sqlalchemy as sa


revision = 'fd63ab5ecf74'
down_revision = 'a72d333806d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medicine_adherence',
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('dose_date', sa.Date(), nullable=False),
    sa.Column('dose_period', sa.String(length=40), nullable=False),
    sa.Column('dose_time', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('confirmed_by_account_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['confirmed_by_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['medicine_schedules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medicine_adherence_dose_date'), 'medicine_adherence', ['dose_date'], unique=False)
    op.create_index(op.f('ix_medicine_adherence_profile_id'), 'medicine_adherence', ['profile_id'], unique=False)
    op.create_index(op.f('ix_medicine_adherence_schedule_id'), 'medicine_adherence', ['schedule_id'], unique=False)
    op.add_column('accounts', sa.Column('preferred_language', sa.String(length=8), nullable=False, server_default='en'))
    op.add_column('hospitals', sa.Column('address', sa.String(length=255), nullable=True))
    op.add_column('hospitals', sa.Column('latitude', sa.Numeric(precision=10, scale=6), nullable=True))
    op.add_column('hospitals', sa.Column('longitude', sa.Numeric(precision=10, scale=6), nullable=True))
    op.add_column('hospitals', sa.Column('phone', sa.String(length=40), nullable=True))
    op.add_column('hospitals', sa.Column('emergency_available', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('hospitals', sa.Column('working_hours', sa.String(length=120), nullable=True))
    op.add_column('medicine_schedules', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('medicine_schedules', sa.Column('end_date', sa.Date(), nullable=True))
    op.add_column('medicine_schedules', sa.Column('forever_medication', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('medicine_schedules', sa.Column('times_per_day', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('medicine_schedules', sa.Column('dose_morning', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('medicine_schedules', sa.Column('dose_afternoon', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('medicine_schedules', sa.Column('dose_evening', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('medicine_schedules', sa.Column('dose_night', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('medicine_schedules', sa.Column('food_timing', sa.String(length=40), nullable=False, server_default='After Food'))
    op.add_column('medicine_schedules', sa.Column('quantity_per_dose', sa.String(length=40), nullable=False, server_default='1'))
    op.add_column('medicine_schedules', sa.Column('unit', sa.String(length=40), nullable=False, server_default='Tablet'))
    op.add_column('medicine_schedules', sa.Column('repeat_pattern', sa.String(length=40), nullable=False, server_default='Daily'))
    op.add_column('medicine_schedules', sa.Column('repeat_days', sa.String(length=80), nullable=True))
    op.add_column('medicine_schedules', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medicine_schedules', 'notes')
    op.drop_column('medicine_schedules', 'repeat_days')
    op.drop_column('medicine_schedules', 'repeat_pattern')
    op.drop_column('medicine_schedules', 'unit')
    op.drop_column('medicine_schedules', 'quantity_per_dose')
    op.drop_column('medicine_schedules', 'food_timing')
    op.drop_column('medicine_schedules', 'dose_night')
    op.drop_column('medicine_schedules', 'dose_evening')
    op.drop_column('medicine_schedules', 'dose_afternoon')
    op.drop_column('medicine_schedules', 'dose_morning')
    op.drop_column('medicine_schedules', 'times_per_day')
    op.drop_column('medicine_schedules', 'forever_medication')
    op.drop_column('medicine_schedules', 'end_date')
    op.drop_column('medicine_schedules', 'start_date')
    op.drop_column('hospitals', 'working_hours')
    op.drop_column('hospitals', 'emergency_available')
    op.drop_column('hospitals', 'phone')
    op.drop_column('hospitals', 'longitude')
    op.drop_column('hospitals', 'latitude')
    op.drop_column('hospitals', 'address')
    op.drop_column('accounts', 'preferred_language')
    op.drop_index(op.f('ix_medicine_adherence_schedule_id'), table_name='medicine_adherence')
    op.drop_index(op.f('ix_medicine_adherence_profile_id'), table_name='medicine_adherence')
    op.drop_index(op.f('ix_medicine_adherence_dose_date'), table_name='medicine_adherence')
    op.drop_table('medicine_adherence')
    # ### end Alembic commands ###
